#!/bin/sh
module="minesweeper"
mode="777"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# Retrieve the major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stalespecial nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

mknod /dev/${1} c $major 0
chgrp $group /dev/${1}
chmod $mode  /dev/${1}
