#!/bin/sh
module="minesweeper"
device="minesweeper"
mode="777"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# Invoke insmod
insmod ./$module.ko board_w=$1 board_h=$2 bomb_count=$3 || exit 1

# Retrieve the major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stalespecial nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}
